apiVersion: v1
kind: Service
metadata:
  name: price-search
  labels:
    app: price-search
spec:
  type: NodePort
  ports:
  - name: server
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: price-search